CREATE VIEW TestView_View1
AS
SELECT kh.MaKH, kh.TenKH, kh.DiaChi 
FROM KHACHHANG kh
JOIN HOADON hd on kh.MaKH = hd.MaKH
JOIN CHITIETHOADON ct on hd.MaHD = ct.MaHD
JOIN VATTU vt on ct.MaVT = vt.MaVT
WHERE vt.TenVT = 'Gach Ong'
GO;

SELECT * FROM TestView_View1

SELECT * FROM CHITIETHOADON
SELECT * FROM HOADON
SELECT * FROM KHACHHANG